nohup python3 test.py --layers 1 --method bayes > bayes_1.out &
nohup python3 test.py --layers 2 --method bayes > bayes_2.out &
nohup python3 test.py --layers 3 --method bayes > bayes_3.out &
nohup python3 test.py --layers 4 --method bayes > bayes_4.out &
nohup python3 test.py --layers 5 --method bayes > bayes_5.out &
nohup python3 test.py --layers 6 --method bayes > bayes_6.out &
nohup python3 test.py --layers 7 --method bayes > bayes_7.out &
nohup python3 test.py --layers 8 --method bayes > bayes_8.out &
nohup python3 test.py --layers 9 --method bayes > bayes_9.out &
nohup python3 test.py --layers 10 --method bayes > bayes_10.out &
